# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode 8.3
language: objective-c
cache:
  - bundler
  - cocoapods
podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - gem install xcpretty -N
# - pod update --project-directory=Example
# - pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/Heartland-iOS-SDK.xcworkspace -scheme Heartland-iOS-SDK-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
# Following extra lines added for automate cocoapod release 
# Late if need can follow https://fuller.li/posts/automated-cocoapods-releases-with-ci/ 

deploy:
  provider: script
  script: ./scripts/push.sh production $TRAVIS_TAG
  skip_cleanup: true
  on:
    branch: master
    tags: false
